alias gadd='git add'
alias gcommit='git commit -m'
alias gcheckout='git checkout'
alias gdiff='git diff'
alias glog='git log'
alias gpull='git pull'
alias gpush='git push'
alias greset='git reset --soft'
alias grm='git rm'
alias gstatus='git status'

alias containers-up='docker-compose up -d'
alias containers-down='docker-compose down'
# alias web-container='docker exec -it $(basename $(pwd))_web_1 su docker -s /bin/ash'
