filetype plugin on
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

call pathogen#helptags()

syntax on
set nocompatible

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent

set nobomb
set number relativenumber

set laststatus=2

set tags=./tags;$HOME

let g:NERDComMappings = 0
let g:DisableAutoPHPFolding = 1

let g:ctrlp_map = '<Leader>f'
let g:ctrlp_cmd = 'CtrlPLastMode'

let g:vdebug_options = {
\   'port': 9000,
\   'break_on_open': 0,
\   'path_maps': {}
\}

autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p

" ***********
" ** STYLE **
" ***********
if has('gui_running')
    set guifont=Source\ Code\ Pro\ 12
    colorscheme darkspectrum
else
    set term=xterm-256color
    set mouse=a
endif

" ******************
" ** MAPPING KEYS **
" ******************
let mapleader = "\<Space>"

" PLUGINS
nnoremap <Leader>d :NERDTreeMirror<CR>
nnoremap <Leader>D :NERDTreeClose<CR>
nnoremap <Leader>/ :TagbarToggle<CR>
map <Leader>; <plug>NERDCommenterToggle

" FUGITIVE (GIT)
nnoremap <Leader>gs :Gstatus<CR>
nnoremap <Leader>gc :Gcommit<CR>
nnoremap <Leader>gd :Gdiff<CR>

" SURROUND
nnoremap <Leader>i yss<em>
nnoremap <Leader>b yss<strong>
nnoremap <Leader>' yss'
nnoremap <Leader>" yss"
nnoremap <Leader>9 yss)

" FOLDING
nnoremap <Leader>- :EnableFastPHPFolds<CR>
nnoremap <Leader>= :DisablePHPFolds<CR>
nnoremap = zo
nnoremap - zc

" TABS
nnoremap <Leader>t :tabnew<CR>
nnoremap <Leader>w :tabclose<CR>
nnoremap <Leader>n :tabnext<CR>
nnoremap <Leader>p :tabprevious<CR>

" DOCUMENT
nnoremap <Home> gg
nnoremap <End> G

nnoremap <Leader>o :e<Space>
nnoremap <Leader>q :q<CR>
nnoremap <Leader>s :w<CR>
nnoremap <Leader>N :new<CR>

" LINE POSITION
nnoremap H ^
nnoremap L $

" SPLITS
nnoremap <Leader>h :split<CR>
nnoremap <Leader>v :vsplit<CR>

" NAVIGATION
nnoremap <Leader><Up> <C-w>k
nnoremap <Leader><Down> <C-w>j
nnoremap <Leader><Left> <C-w>h
nnoremap <Leader><Right> <C-w>l

" COPY/PASTE
nnoremap <Leader>V "+p
vnoremap <Leader>C "+y

" MOVING LINES
nnoremap <S-Up> ddkP
nnoremap <S-Down> ddjP

" JUMPS
nnoremap <C-Left> <C-O>
nnoremap <C-Right> <C-I>
